# Generated by Django 4.2.4 on 2024-07-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='images/default_profile.JPG', null=True, upload_to='images/'),
        ),
    ]
