# Generated by Django 4.2.4 on 2024-07-27 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritedoctor',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='favoritedoctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='FavoriteDoctor',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
