# Generated by Django 4.2.4 on 2024-07-28 16:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0005_alter_doctor_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritedoctor',
            unique_together={('user', 'doctor')},
        ),
    ]
